# Election Results

You’re part of an impartial research group that conducts phone surveys prior to local elections. During this election season, the group conducted a survey to determine how many people would vote for I_Khan vs. S_Sharif in the presidential election.

Now that the election has occurred, your group wants to compare the survey responses to the actual results.

Was your survey a good indicator? Let’s find out!

# PROJECT STEPS

1.First, import numpy and matplotlib.

In [2]:
#type your code here

import numpy as np

import matplotlib as mp

2.There is a list given of the different survey responses.

Calculate the number of people who answered ‘I_Khan’ and save the answer to the variable total_Khan.

Print the variable to the terminal to see its value.

In [17]:
survey_responses = ['I_Khan', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan','S_Sharif',
                    'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif',
                    'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif','I_Khan', 'I_Khan', 
                    'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 
                    'I_Khan', 'I_Khan', 'I_Khan', 'I_Khan', 'I_Khan', 'I_Khan',
                    'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif',
                    'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 
                    'I_Khan', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif',
                    'S_Sharif', 'I_Khan','S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 
                    'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 
                    'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'S_Sharif', 
                    'S_Sharif', 'S_Sharif', 'S_Sharif', 'I_Khan']

print(survey_responses)

['I_Khan', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'I_Khan', 'I_Khan', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'S_Sharif', 'I_Khan']


3.Calculate the percentage of people in the survey who voted for I_Khan and save it to the variable percentage_I_Khan.

Print the variable to the terminal to see its value.

In [31]:
#type your code here
Total_Responses = sum(np.char.count(survey_responses,'a'))
print(Total_Responses)
Count_I_Khan = sum(np.char.count(survey_responses,'Khan')) 
print(Count_I_Khan)
percentage_I_Khan = (Count_I_Khan / Total_Responses)*100
percentage_I_Khan

70
33


47.14285714285714

4.In the real election, 54% of the 10,000 town population voted for I_Khan. Your supervisors are concerned because this is a very different outcome than what the poll predicted. They want you to determine if there is something wrong with the poll or if given the sample size, it was an entirely reasonable result.

Generate a binomial distribution that takes the number of total survey responses, the actual success rate, and the size of the town’s population as its parameters. Then divide the distribution by the number of survey responses. Save your calculation to the variable possible_surveys.

######### hint###########
possible_surveys = 
np.random.binomial(total of survey responses, the actual success rate,and the size of the town’s population ) 

In [53]:
#type your code here
possible_surveys = np.random.binomial(Total_Responses, 0.54,70)
possible_surveys

array([42, 31, 37, 38, 34, 37, 34, 39, 40, 34, 37, 26, 41, 37, 36, 45, 33,
       39, 40, 34, 42, 40, 37, 40, 35, 34, 34, 33, 36, 37, 38, 35, 32, 33,
       34, 42, 34, 36, 40, 40, 43, 31, 39, 43, 34, 36, 38, 37, 38, 41, 41,
       35, 34, 34, 39, 44, 43, 38, 36, 39, 36, 40, 43, 33, 46, 42, 39, 41,
       42, 38])


      #######Optional########
5.By using matplotlib Plot a histogram of possible_surveys with a range of 0-1 and 20 bins.


In [43]:
#type your code here



6.As we saw, 47% of people we surveyed said they would vote for I_Khan, but 54% of people voted for I_Khan in the actual election.

Calculate the percentage of surveys that could have an outcome of I_Khan receiving less than 50% of the vote and save it to the variable I_Khan_loss_surveys.

Print the variable to the terminal.

In [54]:
#type your code here
I_Khan_loss_surveys = possible_surveys[possible_surveys<35]
I_Khan_loss_surveys

array([31, 34, 34, 34, 26, 33, 34, 34, 34, 33, 32, 33, 34, 34, 31, 34, 34,
       34, 33])

7.With this current poll, about 20% of the time a survey output would predict S_Sharif winning, even if I_Khan won the actual election.

Your co-worker points out that your poll would be more accurate if it had more responders.

Generate another binomial distribution, but this time, see what would happen if you had instead surveyed 7,000 people. Divide the distribution by the size of the survey and save your findings to large_survey.


In [55]:
#type your code here
large_survey = np.random.binomial(Total_Responses, 0.54,7000)
large_survey


array([36, 32, 43, ..., 40, 39, 40])

8.Now, recalculate the percentage of surveys that would have an outcome of I_Khan losing and save it to the variable I_Khan_loss_new, and print the value to the terminal.

What do we notice about this new value?

What advice would you give to your supervisors about predicting results from surveys?


In [56]:
#type your code here

I_Khan_loss_new = large_survey[large_survey<35]
I_Khan_loss_new

array([32, 32, 32, ..., 34, 31, 27])